version: '3.7'

networks:
    spark-network:
        driver: bridge
        ipam:
            driver: default

services:
    spark-master:
        command: bash -c 'start-master.sh && tail -f /dev/null'
        container_name: spark-master
        environment:
            - SPARK_CONF_DIR=/conf
        expose:
            - ${SPARK_MASTER_WEBUI_PORT}
            - ${SPARK_DRIVER_WEBUI_PORT}
            - ${SPARK_MASTER_PORT}
        hostname: ${SPARK_MASTER_HOST}
        image: petersontylerd/spark-cluster:latest
        networks:
            - spark-network
        ports:
            - ${SPARK_MASTER_PORT}:${SPARK_MASTER_PORT}
            - ${SPARK_MASTER_WEBUI_PORT}:${SPARK_MASTER_WEBUI_PORT}
            - ${SPARK_DRIVER_WEBUI_PORT}:${SPARK_DRIVER_WEBUI_PORT}
        volumes:
            - app_history:/${SPARK_HISTORY_DIR}
            - ./conf/master:/conf
            - ../:/home


    spark-worker:
        command: bash -c 'start-slave.sh ${SPARK_MASTER} && tail -f /dev/null'
        depends_on:
            - spark-master
        environment:
            - SPARK_CONF_DIR=/conf
        expose:
            - ${SPARK_MASTER_WEBUI_PORT}
        image: petersontylerd/spark-cluster:latest
        networks:
            - spark-network
        ports:
            - ${SPARK_MASTER_WEBUI_PORT}
        volumes:
            - app_history:/${SPARK_HISTORY_DIR}
            - ./conf/worker:/conf
            - ../:/home

    spark-history:
        hostname: spark-history
        container_name: spark-history
        image: petersontylerd/spark-cluster:latest
        command: bash -c 'start-history-server.sh && tail -f /dev/null'
        environment:
            - SPARK_CONF_DIR=/conf
        expose:
            - ${SPARK_HISTORY_WEBUI_PORT}
        networks:
            - spark-network
        ports:
            - ${SPARK_HISTORY_WEBUI_PORT}:${SPARK_HISTORY_WEBUI_PORT}
        volumes:
            - app_history:/${SPARK_HISTORY_DIR}
            - ./conf/history:/conf

volumes:
    app_history:

